apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-vpa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: vpa-container
        image: amsy810/tools:v2.0
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 10Mi