apiVersion: apps/v1
kind: Deployment
metadata:
        labels:
                app: app
        name: app
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: app
        template:
                metadata:
                        labels:
                                app: app
                spec:
                        containers:
                                - image: yuta42173/pytorch-app:latest
                                  name: pytorch
                                  ports:
                                          - containerPort: 8080
                                  resources:
                                          limits:
                                                  cpu: 50m
                                  command: ["tail", "-f", "/dev/null"]
                                  volumeMounts:
                                          - name: claim-volume
                                            mountPath: /work
                        volumes:
                                - name: claim-volume
                                  persistentVolumeClaim:
                                          claimName: pv-standard-claim
